#!/bin/bash

# Create the session to be used
tmux new-session -d -s closer

# split the window
tmux split-window -v
tmux split-window -h
tmux select-pane -t 1
tmux split-window -h

# Run commands
tmux send-keys -t 1 "cd ~/Code/closer/ && clearpid" enter;
tmux send-keys -t 2 "cd ~/Code/closer/" enter
sleep 4s;
tmux send-keys -t 3 "cd ~/Code/closer-chrome/ && docker-compose up -d" enter;
tmux send-keys -t 4 "cd ~/Code/closer-chrome/ && code ." enter

tmux send-keys -t 3 "react-devtools" enter

# attach to shell
tmux select-pane -t 4
tmux attach-session
