#!/bin/bash

# Create the session to be used
tmux new-session -d -s vagrant

# Run commands
tmux send-keys -t 1 "cd ~/Code/nemo && vagrant up" enter;
tmux send-keys -t 1 "1" enter;
tmux send-keys -t 1 "1" enter;

tmux attach-session
