#!/bin/bash

# Create the session to be used
tmux new-session -d -s promote

# split the window
tmux split-window -v
tmux split-window -h
tmux select-pane -t 1
tmux split-window -h

# Run commands
tmux send-keys -t 1 "cd ~/Code/nemo/promote && vagrant ssh re" enter
sleep 1s
tmux send-keys -t 2 "cd ~/Code/nemo/promote && yarn test --watch" enter
tmux send-keys -t 3 "cd ~/Code/nemo/promote && vagrant ssh re" enter
tmux send-keys -t 4 "cd ~/Code/nemo/promote" enter

# attach to shell
tmux select-pane -t 1
tmux send-keys "bin/rails s" enter
tmux select-pane -t 3
tmux send-keys "yarn start" enter
tmux select-pane -t 4
tmux attach-session
