#!/bin/bash

# bring all docker containers down
cd ~/Code/nemo;
docker-compose down;

cd ~/Code/promote;
docker-compose down;
docker-sync stop;
docker-sync clear;

cd ~/Code/closer;
docker-compose down;

cd ~/Code/closer-chrome;
docker-compose down;

tmux kill-session -t promote
